import React from 'react'
import Navbar from '../Components/Navbar'

const PrivacyPolicy = () => {
  return (
    <>
    <Navbar/>
    <section className="text-gray-600 body-font">
  <div className="container lg:w-2/3 px-5 py-10 mx-auto">
    <div className="flex flex-col w-full mb-20">
      <h2 className="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1 text-center">Effective Date: 20th June 2023</h2>
      <h1 className="text-center sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">PRIVACY POLICY</h1>
      
      </div>
     <div>
  <h1 className="text-2xl font-bold mt-2 mb-4">INTRODUCTION</h1>
  <p>We value the privacy of our users and are committed to protecting their personal information. This Privacy Policy explains how we collect, use, store, and disclose the information we collect from you when you use our application, Handdle which is downloadable from Android PlayStore and Apple App Store. This policy also outlines your rights and choices with respect to your personal information. This privacy policy is made in accordance with all the International Privacy Standards and laws such as GDPR, CCPA, and CalOPPA which ensures the privacy of our users.</p>
  <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">INTERPRETATION</h2>
  <p>In this Privacy Policy, the terms with initial capital letters have defined meanings as follows:</p>
  <ul className="list-disc ml-6">
    <li><strong>Country:</strong> refers to the Nigeria</li>
    <li><strong>Device:</strong> means any device that can access the Service, such as a computer, cellphone, or digital tablet.</li>
    <li><strong>Personal:</strong> refers to any information that relates to an identified or identifiable individual.</li>
    <li><strong>Service Provider:</strong> means any natural or legal person who processes data on behalf of our app. It refers to third-party companies or individuals employed by our company to facilitate the Service, to provide the Service on behalf of our company, to perform services related to the Service, or to assist our company in analyzing how the Service is used.</li>
    <li><strong>Usage Data:</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
    <li><strong>App:</strong> refers to Handdle.</li>
    <li><strong>You:</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
  </ul>
  <h2 className="text-2xl font-bold mt-8 mb-4">CONSENT</h2>
  <p>By using our app, you hereby consent to our Privacy Policy and agree to its terms.</p>
  <h2 className="font-bold text-2xl">INFORMATION WE COLLECT</h2>
  <p><strong>Personally Identifiable Information</strong></p>
  <p>When you register or set up your personal profile page on our app, Handdle, you will be required to provide us with personally identifiable information, including your mobile phone number, email address, nickname, photo and video, as well as demographic information such as gender and self-description. Additionally, if you choose to withdraw monetary rewards, you will need to provide us with your financial information, such as your bank account number. While providing personal information is optional, not providing it may limit your access to certain features of the Application.</p>
  <p><strong>Derivative Data</strong></p>
  <p>When you access the Application, our servers automatically collect certain information, such as your IP address, browser type, operating system, access times, and the pages you have viewed before and after accessing the Application. This information may also include your device name and type, operating system, phone number, country, and interactions with the Application and other users. You have the choice to provide additional information at your.
    Free Research Preview. ChatGPT may produce inaccurate information about people, places, or facts. ChatGPT May 24 Version
  </p>
  <h3 className="font-bold">IN-APP COMMUNICATIONS</h3>
  <p>To provide chat services, we store and process the content of your group chats and private chats. This includes scanning for malicious content, detecting spam, abuse, prohibited images, and addressing reported issues. We may use information about your communications (excluding content) to improve our services, enhance the safety of the application, and deliver more relevant content. We do not use chat content to serve ads. We may collect the content you type in the chat box before sending it, in order to provide GIF recommendations. Please note that recipients of your private chats may duplicate, store, or re-share the messages even if you delete them from your account. We also collect content that you post through the Application, such as videos, photos, texts, and comments on other users' posts.</p>
  <h3 className="font-bold">GEO-LOCATION INFORMATION</h3>
  <p>With your consent, we may request access to or permission to track location-based information on your mobile device to provide location-based services. This includes sharing your location with others or using features like Explore. You can manage our access or permissions in your device settings.</p>
  <h3 className="font-bold">MOBILE DEVICE DATA</h3>
  <p>To provide certain features of the chat and messaging service, we may request access or permission to specific features from your mobile device, such as the camera, contacts, microphone, phone, location, SMS messages, and storage. These permissions are necessary for the proper functioning of the Application. We may collect device information, such as your mobile device ID, model, manufacturer, operating system, version information, and IP address, to optimize the performance of the Application.</p>
  <h3 className="font-bold">PUSH NOTIFICATIONS</h3>
  <p>With your permission, we may send push notifications regarding your account or the Application. You have the option to disable these notifications in your smartphone device's system settings.</p>

  <div>
  <h2 className="text-2xl font-bold mt-8 mb-4">HOW WE UTILIZE YOUR INFORMATION</h2>
  <p>We want to be transparent about how we use the information we collect from you. Here is a clear breakdown of how we use your data:</p>
  <h3 className="font-bold">Registration and Account Setup:</h3>
  <p>We use the information you provide to complete your registration on the Application and establish your account, including creating your personal profile page. This allows you to fully utilize the features of the Application.</p>
  <h3 className="font-bold">Internal Data Analysis:</h3>
  <p>We conduct internal data analysis to gain insights and improve the quality of our services. This helps us understand user behavior and preferences, leading to a better user experience.</p>
  <h3 className="font-bold">Chatting Services:</h3>
  <p>We utilize your data to provide various chatting-related services. This includes enabling users to connect with others through phone contacts or other means. Additionally, we recommend GIFs based on the content you input in the chat box, enhancing your messaging experience.</p>
  <h3 className="font-bold">Advertising and Marketing:</h3>
  <p>We may use user-generated content, such as photos and videos, as part of our advertising and marketing campaigns to promote the Application. This helps us reach a wider audience and showcase the features and benefits of our app.</p>
  <h3 className="font-bold">Statistical Analysis:</h3>
  <p>We compile anonymous statistical data and perform analysis, both internally and with third parties, to understand usage patterns and trends. This data is used to improve our services and make informed business decisions.</p>
  <h3 className="font-bold">Personalized Experience:</h3>
  <p>By analyzing your data, we create a personal profile to enhance your future visits to the Application. This includes recommending users who may share similar interests or preferences. With your consent, we may also recommend you to other users, providing opportunities for meaningful connections.</p>
  <h3 className="font-bold">Usage Monitoring and Analysis:</h3>
  <p>We monitor and analyze how you use the Application to improve its efficiency and functionality. This helps us identify areas for enhancement and ensures a seamless user experience.</p>
  <h3 className="font-bold">Application Updates:</h3>
  <p>We use your data to notify you about updates to the Application. This ensures that you have the latest features, bug fixes, and security enhancements.</p>
  <h3 className="font-bold">Product and Service Offerings:</h3>
  <p>Unless you inform us otherwise, we may use your data to inform you about our new products, services, and recommendations. This allows us to provide tailored offerings that align with your interests and preferences.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">Interactive Features:</h2>
  <p>You can engage in interactive features within the Application, and we utilize your data to enable these functionalities. This includes features such as voice messaging, location-based functionality, and SMS-based security verification.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">Law Enforcement Assistance:</h2>
  <p>In compliance with applicable laws, we may assist law enforcement agencies and respond to subpoenas when necessary. This helps maintain the safety and security of our users and the Application.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">Fraud Prevention and Security:</h2>
  <p>We employ measures to prevent fraudulent transactions, monitor against theft, and protect against criminal activity. This ensures the integrity and security of our platform and the information shared within it.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">Feedback:</h2>
  <p>We may use your data to request feedback from you to improve our services, and we may contact you regarding your usage of the Application. Your input is valuable in shaping our ongoing development efforts.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">Resolve disputes:</h2>
  <p>In the event of a dispute or disagreement, we may use your data to investigate and resolve the issue in a fair and efficient manner. This may involve analyzing relevant information and communicating with all parties involved to reach a satisfactory resolution.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">Troubleshoot problems:</h2>
  <p>If you encounter any technical difficulties or experience problems while using our services, we may utilize your data to troubleshoot and identify the root cause of the issue. This allows us to provide you with prompt assistance and ensure a smooth user experience.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">Respond to product and customer service requests:</h2>
  <p>When you reach out to us with product-related inquiries or require customer service support, we will use the data you provide to address your requests and provide appropriate assistance. This may involve gathering additional information from you to better understand and resolve your concerns.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">WHERE DO WE STORE YOUR DATA</h2>
  <p>We store your all data in a secured encrypted database.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">DATA RETENTION DURATION</h2>
  <p>We retain your data for as long as it is necessary to fulfill the purposes outlined in our Terms. However, in certain circumstances, we may retain some of your information even after you cease using our services. This retention is done to comply with our legal obligations, which may include obligations related to tax and accounting requirements.</p>
  <p>We ensure that your data is only retained for the duration required to achieve the specified purposes. Once the data is no longer necessary and legal obligations have been fulfilled, we take appropriate measures to securely and permanently delete or anonymize your information.</p>
  <p>Please note that the specific duration for which we retain your data may vary depending on the nature of the information and legal requirements applicable to our business. Rest assured, we are committed to handling your data responsibly and in accordance with applicable privacy laws and regulations.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">USE OF GOOGLE ANALYTICS AND OTHER TOOLS:</h2>
  <p>We use Google Analytics or other tools for our services (App) to provide our customers with high-quality services. These tools also provide us with all the necessary information about App statistics, such as who visits our App, the number of visitors to our App, where they come from, which device they use, and other data. It also helps us measure the performance of our App.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">CCPA PRIVACY RIGHTS (DO NOT SELL MY PERSONAL INFORMATION):</h2>
  <p>Our policy is in Compliant with the CCPA and CCPA provides the additional rights to our users based in California. California’s users have the following additional rights.</p>
  <ul className="list-disc ml-6">
    <li>Request that a business that collects a consumer's data disclose the categories and specific pieces of personal data that a business has collected about consumers.</li>
    <li>Request that a business deletes any personal data about the consumer that a business has collected.</li>
    <li>Request that a business that sells a consumer's data, not sell the consumer's data.</li>
  </ul>
  <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">GDPR DATA PROTECTION RIGHTS:</h2>
  <p>We would like to make sure you are fully aware of all of your data protection rights. Every user of EU is entitled to the following:</p>
  <ul className="list-disc ml-6">
    <li>The right to access – You have the right to request copies of your data. We may charge you a small fee for this service.</li>
    <li>The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.</li>
    <li>The right to erasure – You have the right to request that we erase your data, under certain conditions.</li>
    <li>The right to restrict processing – You have the right to request that we restrict the processing of your data, under certain conditions.</li>
    <li>The right to object to processing – You have the right to object to our processing of your data, under certain conditions.</li>
    <li>The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
  </ul>
  <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">CALOPPA (CALIFORNIA ONLINE PRIVACY PROTECTION ACT):</h2>
  <p>Although it does apply to California-based businesses as well, CalOPPA pertains to any company that collects personal information from California residents regardless of where that company is located. Because of the global nature of the internet, this law not only applies to most any business in the USA but it can also be (and has been) enforced in other countries as well. In our case, as we have traffic from all over the world so our privacy policy complies with the CalOPPA as well.</p>
  <p>Note:</p>
  <p>CalOPPA requires that all information we collect about Visitors be listed within our Privacy Policy. This includes both the information you collect directly from users, data that is collected automatically such as IP address, and data you collect from visitor such as email etc. We are providing all such information in our privacy policy so we already fulfilled the criteria of CalOPPA requirement.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">CHANGES TO THIS PRIVACY POLICY:</h2>
  <p>We may update Our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
  <p>We will let you know via email and/or a prominent notice on Our Service, before the change becoming effective and update; last updated; date at the top of this Privacy Policy.</p>
  <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">CHILDREN'S INFORMATION:</h2>
  <p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>
  <p>We do not knowingly collect any Personal Identifiable Information from children under the age 13. Minimum age to use our app is 16 in EEA region and 13 in any other country outside EEA region.</p>
  <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us:</h2>
  <p>For more information, contact us through our email address and phone number provided below;</p>
  <p>Email Address: contact@handdle.net</p>
  <p>Phone Number: +2348065153918</p>
</div>





</div>


      </div>
      </section>
      </>
  )
}

export default PrivacyPolicy